spring:
  application:
    name: bi-aviation

  datasource:
    url: jdbc:mysql://localhost:3306/aircraft?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 950915ggg

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
